title: CTextA
description: A website for the computational text analysis team @TAD Center
theme: just-the-docs

url: https://ctexta.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
