title: CTextA
description: A website for the computational text analysis team @TAD Center
theme: just-the-docs

url: https://ctexta.github.io

search_enabled: false

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-PTRJQKD8BT
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

